@cucumber @readme @integration
Feature: Integration — commitGeneratedReadme on real GitHub

  # This feature requires a real GitHub token.
  # It is excluded from the normal `check` task via @integration tag filter.
  #
  # Prerequisites:
  #   - readme.yml must be present in the working directory, injected by CI:
  #     echo "${{ secrets.README_GRADLE_PLUGIN }}" > readme.yml
  #   - The token in readme.yml must have contents:write permission on the repo.
  #
  # Run manually:
  #   ./gradlew -p readme-plugin cucumberTest -Dcucumber.filter.tags="@integration"
  #
  # Or via GitHub Actions workflow: integration_test.yml (workflow_dispatch)

  Scenario: commitGeneratedReadme pushes generated README to a real GitHub branch
    Given a temporary git repository is set up with remote origin
    And the branch "test/readme-ci" is created and checked out
    And the file "README_truth.adoc" exists with the following content:
      """
      = Integration Test

      This README was generated by the commitGeneratedReadme integration test.
      Branch: test/readme-ci — deleted automatically after the scenario.
      """
    When I am executing the task "commitGeneratedReadme"
    Then the build should succeed
    And the build log should contain "Push effectué avec succès"
    And the file "README.adoc" should exist
