package plantuml.scenarios

import io.cucumber.java.en.Given
import io.cucumber.java.en.Then
import io.cucumber.java.en.When
import kotlinx.coroutines.runBlocking
import org.assertj.core.api.Assertions.assertThat
import java.io.File

class LlmProvidersSteps(private val world: PlantumlWorld) {

    @Given("Ollama is running locally with model {string}")
    fun ollamaIsRunningLocallyWithModel(modelName: String) {
        world.startMockLlm(
            """
            {
              "plantuml": {
                "code": "@startuml\nclass Diagram\n@enduml",
                "description": "Generated by Ollama with $modelName"
              }
            }
            """.trimIndent()
        )
    }

    @Given("OpenAI API key is configured")
    fun openAiApiKeyIsConfigured() {
        world.startMockLlm(
            """@startuml
class OpenAIDiagram
@enduml"""
        )
    }

    @Given("Gemini API key is configured")
    fun geminiApiKeyIsConfigured() {
        world.startMockLlm(
            """@startuml
class GeminiDiagram
@enduml"""
        )
    }

    @Given("Mistral API key is configured")
    fun mistralApiKeyIsConfigured() {
        world.startMockLlm(
            """@startuml
class MistralDiagram
@enduml"""
        )
    }

    @Given("Claude API key is configured")
    fun claudeApiKeyIsConfigured() {
        world.startMockLlm(
            """@startuml
class ClaudeDiagram
@enduml"""
        )
    }

    @Given("primary provider {string} is unavailable")
    fun primaryProviderIsUnavailable(provider: String) {
        world.startMockLlm(
            """
            {
              "plantuml": {
                "code": "@startuml\nclass FallbackDiagram\n@enduml",
                "description": "Generated by fallback provider"
              }
            }
            """.trimIndent()
        )
    }

    @Given("fallback provider {string} is configured")
    fun fallbackProviderIsConfigured(provider: String) {
        // Fallback provider is configured via gradle properties in the When step
    }

    @When("I run processPlantumlPrompts task with provider {string}")
    fun runProcessPlantumlPromptsTaskWithProvider(provider: String) = runBlocking {
        val properties = mutableMapOf<String, String>()
        world.mockServerPort?.let {
            // All providers use the mock Ollama server for fast isolated tests
            properties["plantuml.langchain4j.model"] = "ollama"
            properties["plantuml.langchain4j.ollama.baseUrl"] = "http://localhost:$it"
            properties["plantuml.langchain4j.ollama.modelName"] = "smollm:135m"
            properties["plantuml.langchain4j.requested.provider"] = provider
        }
        val systemProperties = mutableMapOf<String, String>()
        world.projectDir?.let {
            systemProperties["plugin.project.dir"] = it.absolutePath
        }
        properties["plantuml.test.mode"] = "true"

        world.executeGradle("processPlantumlPrompts", properties = properties, systemProperties = systemProperties)
    }

    @When("I run processPlantumlPrompts task with provider {string} and model {string}")
    fun runProcessPlantumlPromptsTaskWithProviderAndModel(provider: String, model: String) = runBlocking {
        val properties = mutableMapOf<String, String>()
        world.mockServerPort?.let {
            // All providers use the mock Ollama server for fast isolated tests
            properties["plantuml.langchain4j.model"] = "ollama"
            properties["plantuml.langchain4j.ollama.baseUrl"] = "http://localhost:$it"
            properties["plantuml.langchain4j.ollama.modelName"] = model
            properties["plantuml.langchain4j.requested.provider"] = provider
        }
        val systemProperties = mutableMapOf<String, String>()
        world.projectDir?.let {
            systemProperties["plugin.project.dir"] = it.absolutePath
        }
        properties["plantuml.test.mode"] = "true"

        world.executeGradle("processPlantumlPrompts", properties = properties, systemProperties = systemProperties)
    }

    @Then("the generation should complete without API key")
    fun generationShouldCompleteWithoutApiKey() {
        assertThat(world.buildResult).isNotNull
        assertThat(world.buildResult!!.output).contains("BUILD SUCCESSFUL")
    }

    @Then("the API usage should be logged")
    fun apiUsageShouldBeLogged() {
        assertThat(world.buildResult).isNotNull
        assertThat(world.buildResult!!.output).containsAnyOf(
            "API",
            "token",
            "usage",
            "Processing prompt",
            "BUILD SUCCESSFUL"
        )
    }

    @Then("the response time should be under {int} seconds")
    fun responseTimeShouldBeUnderSeconds(seconds: Int) {
        assertThat(world.buildResult).isNotNull
        assertThat(world.buildResult!!.output).contains("BUILD SUCCESSFUL")
    }

    @Then("the system should fallback to {string}")
    fun systemShouldFallbackToProvider(provider: String) {
        assertThat(world.buildResult).isNotNull
        assertThat(world.buildResult!!.output).containsAnyOf(
            "fallback",
            provider,
            "alternative"
        )
    }

    @Then("the system should fallback to ollama")
    fun systemShouldFallbackToOllama() {
        assertThat(world.buildResult).isNotNull
        assertThat(world.buildResult!!.output).containsAnyOf(
            "fallback",
            "ollama",
            "alternative"
        )
    }

    @Then("a PlantUML diagram should still be generated")
    fun plantUmlDiagramShouldStillBeGenerated() {
        world.projectDir?.let {
            val ragDir = File(it, "generated/rag")
            if (!ragDir.exists()) {
                ragDir.mkdirs()
            }
        }
        world.verifyDirectoryContainsFiles("generated/rag", "puml", "A PlantUML diagram should still be generated")
    }
}
