package plantuml

import java.io.File

/**
 * Main configuration model for the PlantUML plugin.
 */
data class PlantumlConfig(
    val input: InputConfig = InputConfig(),
    val output: OutputConfig = OutputConfig(),
    val langchain: LangchainConfig = LangchainConfig(),
    val git: GitConfig = GitConfig(),
    val rag: RagConfig = RagConfig()
) {
    companion object {
        fun load(configFile: File): PlantumlConfig {
            // In a real implementation, this would load from YAML
            return PlantumlConfig()
        }
    }
}

data class InputConfig(
    val prompts: String = "prompts",
    val defaultLang: String = "en"
)

data class OutputConfig(
    val diagrams: String = "generated/diagrams",
    val images: String = "generated/images",
    val validations: String = "generated/validations",
    val rag: String = "generated/rag",
    val format: String = "png",
    val theme: String = "default"
)

data class LangchainConfig(
    val maxIterations: Int = 5,
    val model: String = "ollama",
    val validation: Boolean = true,
    val validationPrompt: String = "Rate this diagram on clarity, completeness, and best practices. Return a JSON with 'score' (1-10) and 'feedback' (string) and 'recommendations' (array).",
    val ollama: OllamaConfig = OllamaConfig(),
    val gemini: ApiKeyConfig = ApiKeyConfig(),
    val mistral: ApiKeyConfig = ApiKeyConfig(),
    val openai: ApiKeyConfig = ApiKeyConfig(),
    val claude: ApiKeyConfig = ApiKeyConfig(),
    val huggingface: ApiKeyConfig = ApiKeyConfig(),
    val groq: ApiKeyConfig = ApiKeyConfig()
)

data class GitConfig(
    val userName: String = "github-actions[bot]",
    val userEmail: String = "github-actions[bot]@users.noreply.github.com",
    val commitMessage: String = "chore: update PlantUML diagrams [skip ci]",
    val watchedBranches: List<String> = listOf("main", "develop")
)

data class OllamaConfig(
    val baseUrl: String = "http://localhost:11434",
    val modelName: String = "smollm:135m"
)

data class ApiKeyConfig(
    val apiKey: String = ""
)

data class RagConfig(
    val databaseUrl: String = "",
    val username: String = "",
    val password: String = "",
    val tableName: String = "embeddings"
)

/**
 * Data model representing a PlantUML diagram generated by the LLM.
 */
data class PlantumlDiagram(
    val conversation: List<String>,
    val plantuml: PlantumlCode
)

/**
 * Data model representing PlantUML code with description.
 */
data class PlantumlCode(
    val code: String,
    val description: String
)

/**
 * Data model representing validation feedback from the LLM.
 */
data class ValidationFeedback(
    val score: Int,
    val feedback: String,
    val recommendations: List<String>
)